server:
  host: 0.0.0.0
  port: 8090

display:
  width: 800
  height: 600
  refresh_seconds: 60

dashboard:
  title: ""
  device_name: "BatCave"

clock:
  enabled: true
  format: "12"

location:
  name: "Mira Road, Mumbai"
  latitude: 19.2813
  longitude: 72.8697

weather:
  enabled: true

crypto:
  enabled: true
  currencies:
    - INR
    - USD

qbittorrent:
  enabled: true
  url: "http://192.168.1.2:8181"
  username: "admin"
  password: ""
